export const siteConfig = {
  // ====== CUSTOMIZE THESE FOR EACH TOOL ======
  name: "Markdown Badge Generator",
  title: "Markdown Badge Generator — Free GitHub README Badge Creator",
  description:
    "Create shields.io-style badges for GitHub READMEs instantly. Choose style, color, label, value, and logo — then copy the Markdown or HTML snippet in one click.",
  url: "https://markdown-badge-generator.tools.jagodana.com",
  ogImage: "/opengraph-image",

  // Header
  headerIcon: "Tag",
  brandAccentColor: "#6366f1",

  // SEO
  keywords: [
    "markdown badge generator",
    "github badge maker",
    "shields.io badge generator",
    "readme badge creator",
    "github readme badges",
    "shields io badge",
    "badge generator for github",
    "npm badge generator",
    "license badge generator",
    "build status badge",
    "github actions badge",
    "markdown shields badges",
  ],
  applicationCategory: "DeveloperApplication",

  // Theme
  themeColor: "#7c3aed",

  // Branding
  creator: "Jagodana",
  creatorUrl: "https://jagodana.com",
  twitterHandle: "@jagodana",

  // Social Profiles
  socialProfiles: [
    "https://twitter.com/jagodana",
  ],

  // Links
  links: {
    github:
      "https://github.com/Jagodana-Studio-Private-Limited/markdown-badge-generator",
    website: "https://jagodana.com",
  },

  // Footer
  footer: {
    about:
      "Free online Markdown Badge Generator — create custom shields.io badges for your GitHub READMEs with zero configuration. Pure client-side, no signup required.",
    featuresTitle: "Features",
    features: [
      "All shields.io badge styles",
      "Custom colors & logos",
      "One-click Markdown copy",
      "Preset badge library",
    ],
  },

  // Hero Section
  hero: {
    badge: "Free & Instant",
    titleLine1: "Generate GitHub README",
    titleGradient: "Badges in Seconds",
    subtitle:
      "Build custom shields.io badges visually — pick your style, color, label, and logo, then copy the Markdown snippet straight into your README.",
  },

  // Feature Cards
  featureCards: [
    {
      icon: "🎨",
      title: "All Badge Styles",
      description:
        "Choose from flat, flat-square, for-the-badge, plastic, or social styles — preview updates instantly.",
    },
    {
      icon: "⚡",
      title: "30+ Preset Badges",
      description:
        "Start from common badges: npm version, GitHub license, build passing, coverage, and more.",
    },
    {
      icon: "📋",
      title: "One-Click Copy",
      description:
        "Copy the Markdown snippet, raw URL, or HTML img tag to your clipboard with a single click.",
    },
  ],

  // Related Tools
  relatedTools: [
    {
      name: "README Generator",
      url: "https://readme-generator.tools.jagodana.com",
      icon: "📄",
      description: "Generate a professional GitHub README.md in seconds.",
    },
    {
      name: "Markdown Table Generator",
      url: "https://markdown-table-generator.tools.jagodana.com",
      icon: "📊",
      description: "Create Markdown tables visually and copy instantly.",
    },
    {
      name: "Git Command Builder",
      url: "https://git-command-builder.tools.jagodana.com",
      icon: "🌿",
      description: "Build and learn git commands with an interactive UI.",
    },
    {
      name: "Color Format Converter",
      url: "https://color-format-converter.tools.jagodana.com",
      icon: "🎨",
      description: "Convert between HEX, RGB, HSL, and other color formats.",
    },
    {
      name: "Gradient Generator",
      url: "https://gradient-generator.tools.jagodana.com",
      icon: "🌈",
      description: "Create beautiful CSS gradients with a live preview.",
    },
    {
      name: "Gitignore Generator",
      url: "https://gitignore-generator.tools.jagodana.com",
      icon: "🚫",
      description: "Generate .gitignore files for any project stack.",
    },
  ],

  // HowTo Steps
  howToSteps: [
    {
      name: "Enter badge details",
      text: "Type your badge label (left text), message (right text), and choose a color using the color picker or a preset name.",
      url: "",
    },
    {
      name: "Choose style and logo",
      text: "Select a badge style (flat, for-the-badge, etc.) and optionally add a logo by entering a Simple Icons name.",
      url: "",
    },
    {
      name: "Copy and paste",
      text: "Click 'Copy Markdown' to copy the badge snippet and paste it directly into your GitHub README.md file.",
      url: "",
    },
  ],
  howToTotalTime: "PT1M",

  // FAQ
  faq: [
    {
      question: "What is a Markdown badge and where can I use it?",
      answer:
        "A Markdown badge is a small image generated by shields.io that displays metadata like build status, npm version, or license type. You paste the Markdown snippet into any README.md, GitHub wiki, or documentation site that renders Markdown.",
    },
    {
      question: "Does this badge generator work offline or need a server?",
      answer:
        "The badge builder runs entirely in your browser — no data is sent to any server. The preview fetches the badge image directly from shields.io, which is a free public service.",
    },
    {
      question: "What badge styles are available?",
      answer:
        "Five styles are supported: flat (default), flat-square, for-the-badge (uppercase, bold), plastic (3D gradient), and social (rounded, for follower counts). All styles are generated via shields.io.",
    },
    {
      question: "How do I add a logo to my badge?",
      answer:
        "Enter any Simple Icons slug (e.g. 'github', 'npm', 'typescript', 'react') in the Logo field. You can browse all available slugs at simpleicons.org. Leave blank for a text-only badge.",
    },
    {
      question: "Can I use a custom color for my badge?",
      answer:
        "Yes. Enter any valid hex color (without the # prefix) or a named shields.io color like brightgreen, blue, red, orange, yellow, green, or lightgrey.",
    },
    {
      question: "What is the shields.io URL format?",
      answer:
        "Shields.io uses the pattern: https://img.shields.io/badge/{label}-{message}-{color}?style={style}&logo={logo}. This tool builds that URL for you and provides ready-to-paste Markdown and HTML snippets.",
    },
  ],

  // ====== PAGES ======
  pages: {
    "/": {
      title: "Markdown Badge Generator — Free GitHub README Badge Creator",
      description:
        "Create shields.io-style badges for GitHub READMEs instantly. Choose style, color, label, value, and logo — then copy the Markdown or HTML snippet in one click.",
      changeFrequency: "weekly" as const,
      priority: 1,
    },
  },
} as const;

export type SiteConfig = typeof siteConfig;
